### ISSUE TITLE
Cannot be used in conjunction with FreeDraw

### ISSUE THREAD

**Issue by hrishiballal** [Wildhoney/L.Pather#7]
Firstly, thanks for the great work!

I am new to this project and am trying to use Pather in combination with FreeDraw, so Pather for freedrawing polylines and FreeDraw to draw polygons. This does not seem work in that it conflicts FreeDraw's modes (I guess as expected). Is there a way to use both on the same map?

**Comment by Wildhoney** [comment]
Hmm. I suppose that's going to be quite difficult, because they're going to be vying for control over Leaflet.
- Have you tried removing one completely when activating the other using `removeLayer`?
- How about explicitly setting `pointer-events: none` on the layer you wish to ignore for the time being?

If we could deal with the issues one-by-one, then that's going to be a lot easier to troubleshoot :+1:

**Comment by hrishiballal** [comment]
I actualy did something else: I ask the user what they are trying to draw and then load just that library. I also keep a removelayer as a fail safe.
